apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: worker-to-externalservice
spec:
  podSelector:
    matchLabels:
      app: worker
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: externalservice
    ports:
    - port: 9090
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: externalservice-from-worker
spec:
  podSelector:
    matchLabels:
      app: externalservice
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: worker
    ports:
    - port: 9090
      protocol: TCP