apiVersion: apps/v1 
kind: Deployment
metadata:
  name: server
spec:
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: mastercloudapps/pa-server:1.0
        env:
        - name: MONGO_URL
          value: mongodb://mongodb:27017/
        - name: MONGO_HOST
          value: mongodb
        - name: MONGO_DB_NAME
          value: test
        - name: MONGO_DB_USER
          value: root
        - name: MONGO_DB_PASSWORD
          value: password
        - name: RABBIT_MQ_HOST
          value: rabbitmq
        - name: RABBIT_MQ_CONN_STRING
          value: amqp://rabbitmq:rabbitmq@rabbitmq        
---
apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app: server
spec:
  ports:
  - port: 8080
  selector:
    app: server
  type: LoadBalancer